CREATE TABLE sites (
    id INTEGER PRIMARY KEY,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    element TEXT NOT NULL DEFAULT '{}',  -- JSON 文字列として格納
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);