name = "pup"
compatibility_date = "2024-03-16"

[env.pup-production]
account_id = "534202c9f507412f249e554fc04b4f87"
[[env.pup-production.d1_databases]]
binding = "DB"
database_name = "pup"
database_id = "409eddf6-14f1-4bfe-9d5d-82fc7dfa84e4"

[env.pup-staging]
account_id = "534202c9f507412f249e554fc04b4f87"
[[env.pup-staging.d1_databases]]
binding = "DB"
database_name = "pup"
database_id = "409eddf6-14f1-4bfe-9d5d-82fc7dfa84e4"

[env.products-production]
account_id = "668ea9059163f3fd8df3b6f512d3ab3f"
[[env.products-production.d1_databases]]
binding = "DB"
database_name = "products"
database_id = "a34d8aaf-ce52-4b85-b76b-9807bd58476a"