name = "pup"
compatibility_date = "2025-05-7"

# PUP environment
[env.staging]
account_id = "534202c9f507412f249e554fc04b4f87"
[[env.staging.d1_databases]]
binding = "PUP_DB"
database_name = "pup"
database_id = "409eddf6-14f1-4bfe-9d5d-82fc7dfa84e4"