name: Deploy Test

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH key
        run: |
          echo "${{ secrets.VPS_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Test SSH connection
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no -o IdentitiesOnly=yes git@${{ secrets.VPS_HOST }} "echo '✅ SSH success from GitHub Actions'"
