name: Auto Tagging

on:
  push:
    branches:
      - '*'  # すべてのブランチでタグを作成

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get current branch name
        id: branch
        run: echo "BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get latest tag for the branch
        id: latest-tag
        run: |
          branch_prefix=$(echo "${{ env.BRANCH_NAME }}" | tr '/' '-')  # "/"を"-"に変換
          latest_tag=$(git tag --list "${branch_prefix}-*" | sort -V | tail -n 1)
          if [ -z "$latest_tag" ]; then
            latest_tag="${branch_prefix}-0.0.0"
          fi
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV

      - name: Generate new tag
        id: new-tag
        run: |
          latest_tag=${{ env.LATEST_TAG }}
          base_version=$(echo $latest_tag | sed 's/.*-\([0-9]*\.[0-9]*\.[0-9]*\)/\1/')
          new_tag=$(echo $base_version | awk -F. '{print $1"."$2"."$3+1}')
          branch_prefix=$(echo "${{ env.BRANCH_NAME }}" | tr '/' '-')
          new_tag="${branch_prefix}-${new_tag}"
          echo "NEW_TAG=$new_tag" >> $GITHUB_ENV

      - name: Create and push tag
        run: |
          git tag ${{ env.NEW_TAG }}
          git push origin ${{ env.NEW_TAG }}

      - name: Output new tag
        run: echo "New tag created: ${{ env.NEW_TAG }}"